### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by SocraticBliss** [balika011/belf#1]

**Comment by balika011** [comment]
There is no missing dependencies.
Github fails to tag the correct version of TinyXML. Just grab it [here](https://github.com/icebreaker/TinyXML.git).
Just drop the dll in the loaders folder, just like any other loader.
If it doesn't show up ask hexrays for further help.

**Comment by socraticbliss** [comment]
elfr_mips.h and elfr_ia64.h are not in the 7.0 SDK (you need 7.1 SDK) might want to list that... Also the need for Windows 10 SDK since that is your target...

I see you updated and removed some of the other header files that were not needed, nice.

It would still be better if you properly linked TinyXML, as we can't build it without it...

Looks like currently this build will only work with IDA 7.1...

**Comment by balika011** [comment]
Why don't you just download the sdk from hexrays's website? [idasdk70.zip](https://www.hex-rays.com/products/ida/support/ida/idasdk70.zip)

It was tested on 7.0 and works fine.

**Comment by socraticbliss** [comment]
Unfortunately, I don't have a hexrays online account in order to download it :/ as the download link provided requires registration.
